// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { syncBuiltinESMExports } = require('module')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('browsing', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1440, height: 819 })
    await driver.wait(until.elementLocated(By.css(".MuiPaper-root:nth-child(2) .MuiTypography-root > .MuiTypography-root")), 30000)
    await driver.findElement(By.css(".MuiPaper-root:nth-child(2) .MuiTypography-root > .MuiTypography-root")).click()
    await driver.findElement(By.css(".makeStyles-avatar-9 > .MuiAvatar-img")).click()
    await driver.wait(until.elementLocated(By.css(".MuiPaper-root:nth-child(3) > .MuiCardMedia-root")), 30000)
    await driver.findElement(By.css(".MuiPaper-root:nth-child(3) > .MuiCardMedia-root")).click()
    await driver.wait(until.elementLocated(By.css(".MuiPaper-root:nth-child(3) .MuiTypography-root > .MuiTypography-root")), 30000)
    await driver.findElement(By.css(".MuiPaper-root:nth-child(3) .MuiTypography-root > .MuiTypography-root")).click()
    await driver.findElement(By.css(".makeStyles-avatar-9 > .MuiAvatar-img")).click()
    await driver.wait(until.elementLocated(By.css(".MuiPaper-root:nth-child(4) .MuiTypography-root > .MuiTypography-root")), 30000)
    await driver.findElement(By.css(".MuiPaper-root:nth-child(4) .MuiTypography-root > .MuiTypography-root")).click()
    await driver.findElement(By.css(".makeStyles-avatar-9 > .MuiAvatar-img")).click()
    await driver.wait(until.elementLocated(By.css(".MuiPaper-root:nth-child(5) .MuiTypography-root > .MuiTypography-root")), 30000)
    await driver.findElement(By.css(".MuiPaper-root:nth-child(5) .MuiTypography-root > .MuiTypography-root")).click()
    await driver.findElement(By.css(".makeStyles-avatar-9 > .MuiAvatar-img")).click()
    await driver.wait(until.elementLocated(By.css(".MuiPaper-root:nth-child(6) .MuiTypography-root > .MuiTypography-root")), 30000)
    await driver.findElement(By.css(".MuiPaper-root:nth-child(6) .MuiTypography-root > .MuiTypography-root")).click()
    await driver.wait(until.elementLocated(By.linkText("Robert Downey Jr.")), 30000)
    await driver.findElement(By.linkText("Robert Downey Jr.")).click()
    await driver.findElement(By.css(".makeStyles-avatar-9 > .MuiAvatar-img")).click()
    await driver.close()
  })
  it('loginAndWriteReview', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1440, height: 819 })
    await driver.findElement(By.css(".MuiButton-label")).click()
    await driver.findElement(By.css(".MuiPaper-root:nth-child(2) > .MuiCardMedia-root")).click()
    await driver.findElement(By.css(".MuiPaper-root:nth-child(2) .MuiTypography-root > .MuiTypography-root")).click()
    await driver.findElement(By.css(".jss31:nth-child(3)")).click()
    await driver.findElement(By.css(".jss31:nth-child(3)")).sendKeys("111")
    await driver.findElement(By.css(".MuiButton-text > .MuiButton-label")).click()
    assert(await driver.findElement(By.css(".MuiButtonBase-root:nth-child(23) > .MuiTypography-root:nth-child(2)")).getText() == "111")
  })
  it('searching', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1440, height: 819 })
    await driver.findElement(By.css(".MuiInputBase-input")).click()
    await driver.findElement(By.css(".MuiInputBase-input")).sendKeys("Avenger")
    await driver.findElement(By.css(".MuiInputBase-input")).sendKeys(Key.ENTER)
    vars["title1"] = "css=.MuiButtonBase-root:nth-child(1) > .makeStyles-title-17"
    vars["tmp"] = await driver.executeScript("var t = arguments[0]; return t.includes(\'Avenger\');", vars["title1"])
    console.log(vars["tmp"])
    assert(await driver.findElement(By.css(".MuiButtonBase-root:nth-child(1) > .makeStyles-title-17")).getText() == "Captain America: The First Avenger")
    assert(await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2) > .makeStyles-title-17")).getText() == "The Toxic Avenger")
  })
  it('searchingAndbrowsing', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1440, height: 819 })
    await driver.findElement(By.css(".MuiInputBase-input")).click()
    await driver.findElement(By.css(".MuiInputBase-input")).sendKeys("avenger")
    await driver.findElement(By.css(".MuiInputBase-input")).sendKeys(Key.ENTER)
    await driver.wait(until.elementLocated(By.css(".MuiButtonBase-root:nth-child(1) > .makeStyles-title-17")), 30000)
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(1) > .makeStyles-title-17")).click()
    await driver.wait(until.elementLocated(By.linkText("Sebastian Stan")), 30000)
    await driver.findElement(By.linkText("Sebastian Stan")).click()
    await driver.wait(until.elementLocated(By.css(".MuiTypography-h3")), 30000)
    //console(driver.findElement(By.css(".MuiTypography-h3")).getText());
    assert(await driver.findElement(By.css(".MuiTypography-h3")).getText() == "Sebastian Stan")
  })
})
